# Generated by Django 3.0 on 2020-07-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Element',
            new_name='Task',
        ),
    ]
