# Generated by Django 3.0 on 2020-07-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extest', '0002_auto_20200711_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='heading',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
